---
- name: Register primary node with repmgr
  # noqa no-changed-when
  become: true
  become_user: postgres
  ansible.builtin.command: "{{ postgresql_bin_path }}/repmgr -f /etc/repmgr/{{ postgresql_version_major }}/repmgr.conf primary register"
  when: postgresql_ha_initial_role == "primary"
- name: Stop postgresql service before cloning
  become: true
  ansible.builtin.systemd:
    name: "{{ postgresql_daemon }}"
    state: stopped
  when: postgresql_ha_initial_role == "standby"
- name: Clone to standby node
  # noqa no-changed-when
  become: true
  become_user: postgres
  ansible.builtin.command: >-
    {{ postgresql_bin_path }}/repmgr -h {{ postgresql_repmgr_peer }} -U repmgr -d repmgr
     -f /etc/repmgr/{{ postgresql_version_major }}/repmgr.conf standby clone -F
  when: postgresql_ha_initial_role == "standby"
- name: Start postgresql service after cloning
  become: true
  ansible.builtin.systemd:
    name: "{{ postgresql_daemon }}"
    state: started
  when: postgresql_ha_initial_role == "standby"
- name: Register standby node with repmgr
  # noqa no-changed-when
  become: true
  become_user: postgres
  ansible.builtin.command: "{{ postgresql_bin_path }}/repmgr -f /etc/repmgr/{{ postgresql_version_major }}/repmgr.conf standby register"
  when: postgresql_ha_initial_role == "standby"
